=== shilpa-k29/Employee/cat.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="Christ">
<xs:complexType>
<xs:sequence>
<xs:element name="ComputerScience" maxOccurs="unbounded">
<xs:complexType>
<xs:sequence>

 <xs:element name="Stu-name" type="xs:string"></xs:element>
<xs:element name="stu-uni" type="xs:string"></xs:element>
<xs:element name="stu-pho" type="xs:string"></xs:element>
<xs:element name="stu-email" type="email"></xs:element>

</xs:sequence>
</xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>

<xs:simpleType name="email">
<xs:restriction base="xs:string"><xs:pattern value="[^@]+@[^\.]+\..+"/>
</xs:restriction>
</xs:simpleType>

</xs:schema>

=== shilpa-k29/Employee/cat.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="cat.xsl"?>
<Christ xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cat.xsd">
  <ComputerScience>
    <Stu-name>Sharath</Stu-name>
    <stu-uni>Christ</stu-uni>
    <stu-pho>127867</stu-pho>
    <stu-email>sharath@gmail.com</stu-email>
  </ComputerScience>
   <ComputerScience>
    <Stu-name>shilpa</Stu-name>
    <stu-uni>Christ</stu-uni>
    <stu-pho>987654320</stu-pho>
    <stu-email>shilpa@gmail.com</stu-email>
  </ComputerScience>
   <ComputerScience>
    <Stu-name>sam</Stu-name>
    <stu-uni>Christ</stu-uni>
    <stu-pho>987654210</stu-pho>
    <stu-email>sam@gmail.com</stu-email>
  </ComputerScience>
</Christ>
