=== shilpa-k29/Employee/Employee.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="Companys">
<xs:complexType>
<xs:sequence>
<xs:element name="Employee" maxOccurs="unbounded">
<xs:complexType>
<xs:sequence>
<xs:element name="Emp-id" type="xs:integer"></xs:element>
<xs:element name="Emp-name" type="xs:string"></xs:element>
<xs:element name="Emp-age" type="age"></xs:element>
<xs:element name="Emp-salary" type="salary"></xs:element>
<xs:element name="Emp-emailid" type="email"></xs:element>
<xs:element name="Emp-phonenumber" type="xs:int"></xs:element>
<xs:element name="Emp-designation" type="xs:string"></xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>

<xs:simpleType name="age">
    	<xs:restriction base="xs:integer">
    	<xs:minInclusive value="1"/>
    	<xs:maxExclusive value="100"/>
    </xs:restriction>
</xs:simpleType>
<xs:simpleType name="salary">
    	<xs:restriction base="xs:integer">
    	<xs:minInclusive value="50000"/>
    	<xs:maxExclusive value="200000"/>
    </xs:restriction>
</xs:simpleType>
<xs:simpleType name="email">
<xs:restriction base="xs:string"><xs:pattern value="[^@]+@[^\.]+\..+"/>
</xs:restriction>
</xs:simpleType>

</xs:schema>

=== shilpa-k29/Employee/Employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Employee.xsl"?>
<Companys xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Employee.xsd">
  <Employee>
    <Emp-id>1</Emp-id>
    <Emp-name>Sharath</Emp-name>
    <Emp-age>54</Emp-age>
    <Emp-salary>58000</Emp-salary>
    <Emp-emailid>sharath@gmail.com</Emp-emailid>
    <Emp-phonenumber>9876543210</Emp-phonenumber>
    <Emp-designation>Associate Manager</Emp-designation>
  </Employee>
  <Employee>
    <Emp-id>2</Emp-id>
    <Emp-name>Suman</Emp-name>
    <Emp-age>47</Emp-age>
    <Emp-salary>60000</Emp-salary>
    <Emp-emailid>suman@gmail.com</Emp-emailid>
    <Emp-phonenumber>8769054321</Emp-phonenumber>
    <Emp-designation>Developer</Emp-designation>
  </Employee>
</Companys>
